Hw1
kurbata/andrii_devico_cypress pull request #2
Opened 2022-07-21 17:35 UTC by kurbata

2022-07-25 07:29 UTC, ievgendco requested changes
Too much files was added

2022-07-25 07:32 UTC, ievgendco requested changes

2022-07-25 07:32 UTC, ievgendco commented on cypress/Integrations/ToolsQAShop.feature
> +Feature: Shopping on Tools QA
Are you sure you are using BDD solution for your tests?

2022-07-25 07:32 UTC, ievgendco commented on cypress/e2e/sign_in_page.spec.js
> +
Should be a single space between blocks

2022-07-25 07:32 UTC, ievgendco commented on cypress/e2e/sign_in_page.spec.js
> +    it('should show typeable Password field', () => {
See comment above

2022-08-26 15:30 UTC, kurbata commented on cypress/e2e/sign_in_page.spec.js
> +    it('should show typeable Password field', () => {
Fixed

2022-08-26 15:30 UTC, kurbata commented on cypress/e2e/sign_in_page.spec.js
> +
Fixed

2022-08-31 15:31 UTC, merged